[package]
name = "polars-vol"
version = "0.1.1"
edition = "2021"
description = "Rust-powered Polars expressions for Black-Scholes pricing, Greeks and implied volatility"
license = "MIT"

[lib]
name = "polars_vol"
crate-type= ["cdylib"]

[dependencies]
pyo3 = { version = "0.26.0", features = ["extension-module", "abi3-py39"] }
pyo3-polars = { version = "0.25.0", features = ["derive", "dtype-struct"] }
serde = { version = "1", features = ["derive"] }
polars = { version = "0.52.0", default-features = false }

